/*
CHALLENGE
WRITE A QUERY TO SELECT ALL ROWS AND COLUMNS IN THE EMPLOYEE TABLE
*/
use northwind;

SELECT * FROM Employees;

select * from orders;

/*
CHALLENGE
SELECT ONLY SPECIFIC COLUMNS FROM THE EMPLOYEES TABLE: EmployeeID, FirstName, LastName, and Salary
*/

Select EmployeeID, FirstName, LastName, Salary from employees;

/*
CHALLENGE
YOUR MANAGER WANTS TO SEE ALL THE DETAILS OF THE COMPANY'S CUSTOMERS
*/
SELECT * FROM customers;

/*
CHALLENGE
YOU SENT THE ABOVE RESULT TO HIM BUT HE ASKED YOU TO STREAMLINE THE RESULT TO COMPANYNAME, CONTACTNAME AND ADDRESS. 
*/

SELECT CompanyName, ContactName, Address FROM customers;